//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PR_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TennisPlayer
    {
        public string FIOSportsman { get; set; }
        public string NameSportsman { get; set; }
        public string OtchSportsman { get; set; }
        public string Gender { get; set; }
        public int Birthday { get; set; }
        public string FIOTrener { get; set; }
        public string NameTrener { get; set; }
        public string OtchTrener { get; set; }
        public string Country { get; set; }
        public Nullable<int> Rating2018 { get; set; }
        public Nullable<int> Rating2019 { get; set; }
        public Nullable<int> Rating2020 { get; set; }
        public Nullable<int> Rating2021 { get; set; }
        public Nullable<int> Rating2022 { get; set; }
    }
}
